conversion_electricity_FlexMex2_1:
  EnergyConversion_SecondaryEnergy_Electricity_CH4_GT:
  EnergyConversion_SecondaryEnergy_Electricity_RE:
  EnergyConversion_SecondaryEnergy_Electricity_Slack:
  Transmission_Flows_Electricity_Grid:
  EnergyConversion_Curtailment_Electricity_RE:

conversion_electricity_FlexMex2_2:
 EnergyConversion_SecondaryEnergy_Electricity_CH4_GT:
 EnergyConversion_SecondaryEnergy_Electricity_ElectricityHeat_CH4_ExCCGT:
 EnergyConversion_SecondaryEnergy_Electricity_RE:
 EnergyConversion_SecondaryEnergy_Electricity_Hydro_ReservoirTurbine:
 Transport_FeedIn_DrivePower_Electricity:
 EnergyConversion_SecondaryEnergy_Electricity_Slack:
 EnergyConversion_Curtailment_Electricity_RE:
 Transmission_Flows_Electricity_Grid:

conversion_heat_FlexMex2_2:
  EnergyConversion_SecondaryEnergy_Heat_Electricity_Large:
  EnergyConversion_SecondaryEnergy_Heat_ElectricityHeat_CH4_ExCCGT:
  EnergyConversion_SecondaryEnergy_Heat_ElectricityHeat_Large:
  EnergyConversion_SecondaryEnergy_Heat_ElectricityHeat_Small:
  EnergyConversion_SecondaryEnergy_Heat_Gas_Large:
  EnergyConversion_SecondaryEnergy_Heat_Slack:

electricity_storage_FlexMex2_1:
 Storage_Losses_Electricity_LiIonBatteryStorage:
 Storage_Output_Electricity_LiIonBatteryStorage:

electricity_storage_FlexMex2_2:
  Storage_Losses_Electricity_LiIonBatteryStorage:
  Storage_Losses_H2_H2CavernStorage:
  Storage_Losses_H2_H2TankStorage:
  Storage_Output_Electricity_LiIonBatteryStorage:
  Storage_Output_H2_H2CavernStorage:
  Storage_Output_H2_H2TankStorage:
  Transport_FeedIn_DrivePower_Electricity: #? TODO
  Transport_Shifting_DrivePower_Electricity:

heat_storage_FlexMex2_2:
  Storage_Losses_Heat_LargeStorage:
  Storage_Losses_Heat_SmallStorage:
  Storage_Output_Heat_LargeStorage:
  Storage_Output_Heat_SmallStorage:

